# See https://github.com/google/mono_repo.dart for details on this file
sdk:
- stable

stages:
# Register two jobs to run under the `analyze` stage.
  - analyze:
    - analyze
    - format
  - unit_test:
    - test