version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/application"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/pkg/dropbear"
    schedule:
      interval: "weekly"
