lint:
  directories:
    exclude:
      - pkg/todart_api/protos/google
  rules:
    all_default: true
    add:
      - MESSAGE_NAMES_UPPER_CAMEL_CASE
      - SERVICE_NAMES_UPPER_CAMEL_CASE
      - INDENT
      - PROTO3_FIELDS_AVOID_REQUIRED
      - QUOTE_CONSISTENT
      - REPEATED_FIELD_NAMES_PLURALIZED
      - SERVICE_NAMES_UPPER_CAMEL_CASE
      - RPC_NAMES_UPPER_CAMEL_CASE
      - PACKAGE_NAME_LOWER_CASE
      - ORDER
      - IMPORTS_SORTED
      - FILE_NAMES_LOWER_SNAKE_CASE
      - ENUM_NAMES_UPPER_CAMEL_CASE
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
      - ENUM_FIELD_NAMES_UPPER_SNAKE_CASE
      - ENUM_FIELD_NAMES_PREFIX
   # Linter rules option.
  rules_option:
    # MAX_LINE_LENGTH rule option.
    max_line_length:
      # Enforces a maximum line length
      max_chars: 100
