name: todart_server
description: A sample command-line application.
version: 1.0.0
# Prevent accidental publishing to pub.dev.
publish_to: 'none'
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  args: ^2.3.1
  built_value: ^8.3.2
  get_it: ^7.2.0
  todart_api: 
    path: ../api
  dropbear:
    path: ../pkg/dropbear


dev_dependencies:
  build_runner: ^2.1.11
  built_value_generator: ^8.3.2
  lints: ^1.0.0
  test: ^1.21.1
