# See https://github.com/google/mono_repo.dart for details on this file
sdk:
- stable
- beta

stages:
- smoke_test:
  - group:
    - format
    - analyze: --fatal-infos .
    sdk:
    - beta
    - stable

- test:
  - test: --test-randomize-ordering-seed=random
    os:
    - linux