name: dropbear
description: A starting point for Dart libraries or applications.
version: 1.0.0
# Prevent accidental publishing to pub.dev.
publish_to: 'none'

environment:
  sdk: '>=2.17.6 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: 
  base32: ^2.1.1
  quiver: ^3.0.1+1
