# Created with package:mono_repo v6.2.0
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v3.0.0
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.2.0
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze; PKGS: api, application, server; `dart analyze`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:api-application-server;commands:analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:api-application-server
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v3.0.0
      - id: api_pub_upgrade
        name: api; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: api
        run: dart pub upgrade
      - name: api; dart analyze
        if: "always() && steps.api_pub_upgrade.conclusion == 'success'"
        working-directory: api
        run: dart analyze
      - id: application_pub_upgrade
        name: application; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: application
        run: dart pub upgrade
      - name: application; dart analyze
        if: "always() && steps.application_pub_upgrade.conclusion == 'success'"
        working-directory: application
        run: dart analyze
      - id: server_pub_upgrade
        name: server; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: server
        run: dart pub upgrade
      - name: server; dart analyze
        if: "always() && steps.server_pub_upgrade.conclusion == 'success'"
        working-directory: server
        run: dart analyze
  job_003:
    name: "analyze; PKGS: api, application, server; `dart format --output=none --set-exit-if-changed .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:api-application-server;commands:format"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:api-application-server
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v3.0.0
      - id: api_pub_upgrade
        name: api; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: api
        run: dart pub upgrade
      - name: "api; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.api_pub_upgrade.conclusion == 'success'"
        working-directory: api
        run: "dart format --output=none --set-exit-if-changed ."
      - id: application_pub_upgrade
        name: application; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: application
        run: dart pub upgrade
      - name: "application; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.application_pub_upgrade.conclusion == 'success'"
        working-directory: application
        run: "dart format --output=none --set-exit-if-changed ."
      - id: server_pub_upgrade
        name: server; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: server
        run: dart pub upgrade
      - name: "server; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.server_pub_upgrade.conclusion == 'success'"
        working-directory: server
        run: "dart format --output=none --set-exit-if-changed ."
  job_004:
    name: "unit_test; PKG: api; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:api;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:api
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v3.0.0
      - id: api_pub_upgrade
        name: api; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: api
        run: dart pub upgrade
      - name: api; dart test
        if: "always() && steps.api_pub_upgrade.conclusion == 'success'"
        working-directory: api
        run: dart test
    needs:
      - job_001
      - job_002
      - job_003
  job_005:
    name: "unit_test; PKG: server; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:server;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:server
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v3.0.0
      - id: server_pub_upgrade
        name: server; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: server
        run: dart pub upgrade
      - name: server; dart test
        if: "always() && steps.server_pub_upgrade.conclusion == 'success'"
        working-directory: server
        run: dart test
    needs:
      - job_001
      - job_002
      - job_003
  job_006:
    name: "unit_test; PKG: application; `flutter test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v3
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:application;commands:test_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:application
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: stable
      - id: checkout
        uses: actions/checkout@v3.0.0
      - id: application_pub_upgrade
        name: application; flutter pub pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: application
        run: flutter pub pub upgrade
      - name: application; flutter test
        if: "always() && steps.application_pub_upgrade.conclusion == 'success'"
        working-directory: application
        run: flutter test
    needs:
      - job_001
      - job_002
      - job_003
